#!/usr/bin/env bash

./xarpite/xa -q "$(cat <<'END'
  ERR := s -> EXEC("bash", "-c", %>printf "%s\n" "$1" >&2<%, "--", s)

  gg := IN
    >> JSONSD
    >> FILTER[o -> o.path =~ /\.jpe?g$/i] // JPEG画像のみ

    >> GROUP[by: g -> g.time]   // タイムスタンプが同じ組
    >> FILTER[g -> g.0.?]       // タイムスタンプがないものは除外
    >> FILTER[g -> g.1.$# >= 2] // 重複がない組を除外

    >> TO_ARRAY

  pipe := PIPE << gg() | g => , -> (
    oo := g.1()
      >> SORTR[by: \_.size.+]
      >> TO_ARRAY
    oo() >> DROP[1] | o => (
      OUT << JSON << {
        distance: EXEC("./distance", oo.0.path, o.path).+
        larger: oo.0
        smaller: o
      }
    )
  )

  1 .. 32 | LAUNCH ( => pipe | _() !? (_ => *ERR) )
END
)"
