#!/usr/bin/env bash

xarpite '
  (READ(ARGS.0) >> JSONSD), (READ(ARGS.1) >> JSONSD)
  >> GROUP[by: o -> o.time]
  >> FILTER[g -> g.0 != "" && g.1.$# > 1] | g =>
    g.1 | oo =>
      [
        oo()
        >> SORT[by: o -> o.path::replace(/\.\w+$/g; "")]
        >> SORTR[by: o -> o.size.+]
        //>> DROP[1]
      ]()
  //>> SORT[by: o -> o.path]
  | o => "$%10d(o.size.+)  $%-26s(o.time)  $(o.path)"
  //>> JSON[indent: " "]
' "$1" "$2"
