#!/usr/bin/env bash

./xarpite/xa --jvm -q '
  IN
  >> JSONSD

  >> GROUP[by: \_.image_hash] // 画像のペイロードが完全に同じ組
  >> FILTER[g => ?g.0]        // 画像ハッシュがないファイルを除外
  >> FILTER[g => g.1.$# >= 2] // 重複がない組を除外

  | g => (

    #OUT << g.0

    oo := g.1()
      >> SORT[by: \_.path::replace(/\.[^.]+$/g; "")] // サイズが同じなら名前順
      >> SORTR[by: \_.size.+]                        // サイズが大きいファイルを優先
      >> TO_ARRAY
    oo() >> DROP[1] | o => (
      OUT << "./delete_if_image_hash_match_and_smaller $APOS$(o.path)$APOS $APOS$(oo.0.path)$APOS || exit"
    )

  )
'
