#!/usr/bin/env bash

./xarpite/xa -q '
  OUT << %>
    <meta charset="UTF-8">
    <style>
      .photo {
        max-width: 200px;
        max-height: 200px;
      }
    </style>
  <%

  IN
  >> JSONSD
  >> FILTER[o -> o.time.$# == 26]
  >> GROUP[by: o -> o.time]
  >> FILTER[g -> g.1.$# >= 2]
  | g => (
    OUT << %>
      <h3><%= g.0 %></h3>
      <table>
        <tr>
          <%= (
            g.1()
            >> SORTR[o -> o.size.+]
            | o => %>
              <td>
                <div><img lazyload class="photo" src="<%= o.path::replace[/^\/mnt\/(.)/g] ( m => "file:///$(m.1):" ) %>"></div>
                <div><%= o.size %></div>
              </td>
            <%
          ) %>
        </tr>
      </table>
    <%
  )
'
